# Generated by Django 4.2.10 on 2024-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price_group_course_group_user_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.CharField(choices=[('1', '1 group'), ('2', '2 group'), ('3', '3 group'), ('4', '4 group'), ('5', '5 group'), ('6', '6 group'), ('7', '7 group'), ('8', '8 group'), ('9', '9 group'), ('10', '10 group')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
